name: Generate Snake Modern

on:
  schedule:
    - cron: "0 */12 * * *" # بيشتغل كل 12 ساعة
  workflow_dispatch: # يسمح بتشغيله يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # بيولد التعبان بألوان مودرن مخصصة
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            # النسخة المودرن (ألوان بنفسجي وأزرق)
            dist/github-contribution-grid-snake-dark.svg?color_snake=#8a2be2&color_dots=#161b22,#2d333b,#3e4c59,#4fd6be,#2e8fff

      # بيفتح فرع جديد اسمه output وبيحط فيه الصور
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
